# Generated by Django 3.2.6 on 2021-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
