# Generated by Django 3.2.6 on 2021-12-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0002_alter_post_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
