# Generated by Django 3.2.6 on 2021-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0003_rename_post_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
