# Generated by Django 3.2.6 on 2021-12-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0004_alter_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='post_img',
        ),
    ]
