# Generated by Django 3.2.6 on 2021-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0005_rename_post_posts_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
