# Generated by Django 3.2.6 on 2021-12-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0007_alter_posts_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
