# Generated by Django 3.2.6 on 2021-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0009_auto_20211217_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(blank=True, max_length=200, null=True)),
                ('Last', models.CharField(blank=True, max_length=200, null=True)),
                ('Work', models.CharField(blank=True, max_length=200, null=True)),
                ('Excellence', models.CharField(blank=True, max_length=200, null=True)),
                ('More', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
