# Generated by Django 3.2.6 on 2021-12-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0010_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Work',
            new_name='work',
        ),
    ]
