# Generated by Django 3.2.6 on 2021-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0013_displayusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayusername',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='displayusername',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
