# Generated by Django 3.2.6 on 2021-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0015_connecteduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecteduser',
            old_name='mobile',
            new_name='first_name',
        ),
    ]
