# Generated by Django 3.2.6 on 2021-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0016_rename_mobile_connecteduser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
