# Generated by Django 3.2.6 on 2021-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taneek', '0017_alter_connecteduser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
